config/routes.rb
Pleasegoonsale::Application.routes.draw do
  
  resources :users, :only => [] do
    resources :items, :only=>[:destroy]  do
      get :create, :on => :collection, :constraints => { :user_id => /\S{20}/ }
    end
  end
  devise_for :users
  resources :sale_items
  match 'my_rack' => 'users#my_rack'
  root :to => "users#my_rack"
  
  

end

app/models/color.rb
require 'open-uri' # so we can stream the swatch file
class Color < ActiveRecord::Base
  
  attr_accessor :swatch_url
  
  # validates_presence_of :name, :hex
  # TODO validate hex is unique for a given sku
  
  before_validation :process_swatch
  
  has_many :items, :through => :items_colors
  
  
private
  
  def process_swatch
    i = ChunkyPNG::Image.from_io(open("http://www.anthropologie.com"<<self.swatch_url))
    self.hex = ChunkyPNG::Color.to_hex(i.get_pixel(2,2))[0,7]
  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_accessor  :raw_price
  attr_accessor  :raw_colors

  has_many :my_rack
  has_many :items_colors
  has_many :users, :through => :my_rack
  has_many :colors, :through => :items_colors
  
  validates_uniqueness_of :sku
  validates_presence_of :raw_price

  before_save :store_price_as_cents
  # before_save :process_colors
  
  
  def self.add_item(attrs, user)
    item = Item.find_or_create_by_sku(attrs['sku'], attrs)
    begin
      user.items << item
      item
    rescue StandardError => e
      puts e.inspect
      puts e.backtrace
      item.errors.add_to_base 'This item is already on your rack!'
      return item
    end
  end
  
  def on_sale?
    !!sale_item
  end
  
  def sale_item
    SaleItem.find_by_sku(sku)
  end
  
  def formatted_price
    "$%.2f" % (self.price/100.0)
  end
  
private
  
  def store_price_as_cents
    self.price = (self.raw_price.gsub('$','').to_f * 100).to_i
  end
  
  def process_colors
    #TODO send raw_colors as an array of hashes
    self.raw_colors.each do |color|
      self.colors << Color.create(color.last)
    end if self.raw_colors
  end
end

app/models/items_colors.rb
class ItemsColor   < ActiveRecord::Base
  belongs_to :item
  belongs_to :color
end

app/models/my_rack.rb
class MyRack < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  
  validates_uniqueness_of :item_id, :scope => :user_id, :message => "This item is already on your rack!"
  
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  
  attr_accessor  :raw_sale_price
  attr_accessor  :raw_original_price
  attr_accessor  :raw_colors

  before_save :store_price_as_cents
  before_save :process_colors
  
  has_many :colors, :foreign_key => :sku
  
  validates_presence_of :raw_sale_price
  validates_uniqueness_of :sku
  
  def self.match
    sale_items = SaleItem.all
    items_on_sale = Item.all(:conditions=>["sku in (?)", sale_items.map(&:sku)])
    puts "="*45
    puts "found #{items_on_sale.length} customer saved items on sale"
    puts "="*45
  end
  
  def formatted_sale_price
    "$%.2f" % (self.sale_price/100.0)
  end
  
  def formatted_original_price
    "$%.2f" % (self.original_price/100.0)
  end
  
private
  
  def store_price_as_cents
    self.sale_price = (self.raw_sale_price.gsub('$','').to_f * 100).to_i
    self.original_price = (self.raw_original_price.gsub('$','').to_f * 100).to_i
  end
  
  def process_colors
    self.raw_colors.each do |color|
      self.colors << Color.create(color)
    end if self.raw_colors  
  end
  
end

app/models/sale_item_observer.rb
class SaleItemObserver < ActiveRecord::Observer
  
  # def after_create(sale_item)
  #   item = Item.where(:sku=>sale_item.sku).first
  #   puts "="*45
  #   puts "observer item: #{item.inspect}"
  #   puts "="*45
  #   if item
  #     item.users.each do |user|
  #       puts "="*45
  #       puts "observer user: #{user.inspect}"
  #       puts "="*45
  #       # TODO if user has instant alerts turned on deliver right away
  #        Notify.sale_email(user, [sale_item]).deliver
  #     end
  #   end
  # end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :my_rack
  has_many :items, :through=>:my_rack
  
  before_save :ensure_authentication_token
  
end

app/models/users_items.rb
class UsersItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  
  validates_uniqueness_of :item_id, :scope => :user_id, :message => "This item is already on your rack!"
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def build_bookmarklet
    @bookmarklet = File.read("#{Rails.root}/public/javascripts/bookmarklet.js")
    puts "="*45
    puts @bookmarklet.inspect
    puts "="*45
    puts "="*45
    puts current_user.inspect
    puts request.raw_host_with_port
    puts "="*45
    @bookmarklet.gsub!("<-api_key->", current_user.authentication_token)
    @bookmarklet.gsub!("<-host->", request.raw_host_with_port)
    puts "="*45
    puts @bookmarklet.inspect
    puts "="*45
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def create
    @user = User.first(:conditions=>{:authentication_token => params["user_id"]})
    item = Item.add_item(params['item'], @user) 
    respond_to do |wants|
      if item.errors.on_base
        wants.json{ render :text => params["jsonp"] + "({error: '#{item.errors.on_base}'})"}
      else
        wants.json{ render :text => params["jsonp"] + "(#{item.to_json})"}
      end
    end
  end
  
  def destroy
    @user = User.find(params[:user_id])
    item = Item.find(params[:id])
    @user.items.delete(item)
    respond_to do |wants|
      wants.html { redirect_to my_rack_path }
    end
  end
  
end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :build_bookmarklet, :only=>[:my_rack]
  
  def my_rack
    @items = current_user.items.reverse
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  

  
end

app/views/layouts/application.html.erb
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<meta content="text/html;charset=UTF-8" http-equiv="content-type"/>
		<title>pleasegoonsale.com - we love to shop online. we love to save online.</title>
    <%= include_stylesheets :main, :media => "all" %>
    <%= include_javascripts :main %>
		<script type="text/javascript" language="javascript" charset="utf-8">
		
      //<![CDATA[
      $(function(){
        // pleasegoonsale.init();
      });
      //]]>
    </script>
	</head> 
	<body>
	  <div class="header">
	    <div class="userinfo">
	      <%if user_signed_in? %>
	      <%= link_to current_user.email, edit_user_registration_path %> |
	      <%= link_to "logout", destroy_user_session_path %>
	      <% else %>
	        <%= link_to "login", new_user_session_path %> | 
	        <%= link_to "signup", new_user_registration_path %>
	      <% end %>
	    </div>
	    <div class="logo">
	    </div>
	    notice: <%= flash[:notice] %> <br/>
	  </div>
	  <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/layout.erb
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<meta content="text/html;charset=UTF-8" http-equiv="content-type"/>
		<title>pleaseGOonSale.com - we love to shop online. we love to save online.</title>
		<link type="text/css" rel="stylesheet" media="screen" href="/less/uber.css" />    
    <%= include_stylesheets :main, :media => "all" %>
    <%= include_javascripts :main %>
		<script type="text/javascript" language="javascript" charset="utf-8">
		
      //<![CDATA[
      $(function(){
        // pleasegoonsale.init();
      });
      //]]>
    </script>
	</head> 
	<body>
	  <div class="header">
	    <div class="userinfo">
	      <%if logged_in? %>
  	      <a href="/user/edit"><%= current_user.email  %></a> |
  	      <a href="/logout">logout</a>
	      <% else %>
	        <a href="/login">login</a> | 
	        <a href="/signup">signup</a>
	      <% end %>
	    </div>
	    <div class="logo">
	    </div>
	    notice: <%= flash[:notice] %> <br/>
	  </div>
	  <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notify/sale_email.html.erb
<p>Hey there!</p>

<p><%= @items.length %> items from your pleasegoonsale.com rack have actually gone on sale! </p>

<%for item in @items %>
<div class="name">
  <%= image_tag item.image_url %>
  <p><%= item.name %></p>
 <p> was: <%= item.formatted_original_price %>
  now: <%= item.formatted_sale_price %></p>
  <p><a href="<%= item.store_url %>"> buy it now</a></p>
</div>

<%end%>

<p>See all your items on your <%= my_rack_url :host=>@host %></p>

app/views/sinatra_views/index.erb
<h1>Hello!</h1>
<p>We here at pleaseGOonSale.com love to shop online.</p>
<p>We wanted a way to know when our favorite stuff at our favorite stores goes on sale, and that's where pleaseGOonSale.com comes in!</p>
<p>Simply browse your favorite stores online (like you normally do) and when you've found something you like, just hit the pleaseGOonSale! bookmark and we'll send you and email if that item goes on sale.</p>

app/views/sinatra_views/layout.erb
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<meta content="text/html;charset=UTF-8" http-equiv="content-type"/>
		<title>pleaseGOonSale.com - we love to shop online. we love to save online.</title>
		<link type="text/css" rel="stylesheet" media="screen" href="/less/uber.css" />    
		<link type="text/css" rel="stylesheet" media="screen" href="/css/tipTip.css" />    
		<script src="/js/jquery-1.4.2.min.js" type="text/javascript"></script>
		<script src="/js/underscore.min.js" type="text/javascript"></script>
    <!-- <script src="/js/pleasegoonsale.js" type="text/javascript"></script> -->
		<script type="text/javascript" language="javascript" charset="utf-8">
		
      //<![CDATA[
      $(function(){
        // pleasegoonsale.init();
      });
      //]]>
    </script>
	</head> 
	<body>
	  <div class="header">
	    <div class="userinfo">
	      <%if logged_in? %>
  	      <a href="/user/edit"><%= current_user.email  %></a> |
  	      <a href="/logout">logout</a>
	      <% else %>
	        <a href="/login">login</a> | 
	        <a href="/signup">signup</a>
	      <% end %>
	    </div>
	    <div class="logo">
	    </div>
	    notice: <%= flash[:notice] %> <br/>
	  </div>
	  <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sinatra_views/my_rack.erb
drag this link into your bookmarks:    
<a title="drag this to your bookmarks" href="<%= @bookmarklet %>">pleasegoOnSale!</a>
<h2><%= @items.length %> items</h2>
<table>
<% @items.each do |item| %>
<tr><td colspan=100><h1>Item <%= item.on_sale? ? 'is' : 'is not'  %> on sale<%='!!!' if item.on_sale? %></h1></td></tr>
  <tr>
    <td colspan=100><img src="<%= item.image_url %>"></td>
  </tr>
  <tr style="border-bottom:2px solid #aaa; margin-bottom:10px">  
    <td><%= item.name %></td>
    <td><%= item.formatted_price %></td>
    <td><a href="<%= item.store_url %>">view</a></td>
    <td>in <%#= item.colors.length %> colors: 
      <%# item.colors.each do |color| %>
        <span style="background:<%#= color.hex %>;height:10px; width:10px; margin:5px; padding:3px;"><%#= color.name  %></span>
      <%# end %>
    </td>
    <td><%= item.sku %></td>
    <td> <a href="/item/remove/<%= item.sku %>" method="delete">remove item</a> </td>
  </tr>
<% end %>
</table>

app/views/sinatra_views/user_manager/confirmation.erb
<h1>Firstly, hello!</h1>
<p>
  Welcome to pleaseGOonSale.com. 
</p>
<p>
  To get started, we need you to confirm your account by clicking here: <a href="http://<%= @host %>/confirm/<%= @user.confirmation_code %>">http://<%= @host %>/confirm/<%= @user.confirmation_code %></a>
</p>
<p>
  After you confirm, simply install the bookmarklet into your browser (<a href="http://<%= @host %>/how_it_works">watch the handy instructional video</a>). 
</p>
<p>  
  Then start browsing your favorite stores online (like you normally do) and when you've found something you like, just hit the pleaseGOonSale! bookmark and we'll send you and email if, or slash when, that item goes on sale.</p>
</p>
<p>Thanks,<br/>
Tyler and Carolyn</p>
<div style="text-align:center margin:10px">pleaseGOonSale.com: we love to shop online. we love to save online.</div>

app/views/sinatra_views/user_manager/login.erb
<div class="span-24">
  <div class="span-15 colborder">
    <h2>Login</h2>
    <form method="post" action="/login" id="dummy">
      <fieldset>
        <p><lable>email</lable><br/><input name ="email" value="<%= params[:email] %>"/>
        <p><lable>password</lable><br/><input type="password" name="password"/></p>
        <p><input type="submit" value="Login"></input></p>
      </fieldset>
    </form>
  </div>
</div>

app/views/sinatra_views/user_manager/new.erb
<div class="span-24">
  <div class="span-15 colborder">
    <h2>SignUp</h2>
    <%if @user.errors.any? %>
    <div class="errors">
      <%for error in @user.errors %>
        <%= error.to_yaml %>
      <%end%>
    </div>
    <% end %>
    <form method="post" action="/signup" id="dummy">
      <fieldset>
        <p>
          <label for="name">name:</label><br/>
          <input type="text" name="user[name]" value="<%= @user.name %>">
        </p>
        <p>
          <label for="user">email:</label><br/>
          <input type="text" name="user[email]" value="<%= @user.email %>">
        </p>
        <p>
          <label for="password">password:</label><br/>
          <input type="password" name="user[password]" value="">
        </p> 
        <p><input type="submit" name="" value="sign up!" id="sign up"> </p>
      </fieldset>
    </form>
  </div>
</div>

app/views/sinatra_views/user_manager/show.erb
<h2><%=@user.name %></h2>
<dl>
  <dt>Handle</dt>
  <dd><%=@user.handle %></dd>
  <dt>Birthdate</dt>
  <dd><%=@user.birthdate %></dd>
  <dt>Region</dt>
  <dd><%=@user.region %></dd>
  <dt>Interests</dt>
  <dd><%=@user.interests %></dd>
  <dt>Company Description</dt>
  <dd><%=@user.company_description %></dd>
</dl>

app/views/sinatra_views/user_manager/whoops.erb
Well hmmm, looks like that confirmation code didn't work. 
type in your email and we'll send you a new one.

app/views/users/my_rack.html.erb
drag this link into your bookmarks:    
<a title="drag this to your bookmarks" href="<%= @bookmarklet %>">pleasegoOnSale!</a>
<h2><%= @items.length %> items</h2>
<table>
<% @items.each do |item| %>
<tr><td colspan=100><h1>Item <%= item.on_sale? ? 'is' : 'is not'  %> on sale<%='!!!' if item.on_sale? %></h1></td></tr>
  <tr>
    <td colspan=100><img src="<%= item.image_url %>"></td>
  </tr>
  <tr style="border-bottom:2px solid #aaa; margin-bottom:10px">  
    <td><%= item.name %></td>
    <%if item.on_sale? %>
      <td>now: <%= item.sale_item.formatted_sale_price %> was:<%= item.sale_item.formatted_original_price %></td>
    <% else %>
      <td><%= item.formatted_price %></td>
    
    <% end %>
    <td><a href="<%= item.store_url %>">buy now</a></td>
    <!-- <td>in <%#= item.colors.length %> colors: 
      <%# item.colors.each do |color| %>
        <span style="background:<%#= color.hex %>;height:10px; width:10px; margin:5px; padding:3px;"><%#= color.name  %></span>
      <%# end %>
    </td> -->
    <td><%= item.sku %></td>
    <td><%= button_to "remove item", user_item_path(current_user, item), :method => :delete, :confirm => "Are you sure?"%> </td>
  </tr>
<% end %>
</table>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>